apiVersion: v1
kind: ConfigMap
metadata:
  name: speech-service-config
  namespace: speech-service
data:
  DEFAULT_STT_ENGINE: "yandex"
  DEFAULT_TTS_ENGINE: "yandex"
  YANDEX_STT_URL: "https://stt.api.yandexcloud.kz/stt/v3/recognizeFileAsync"
  YANDEX_TTS_URL: "https://tts.api.yandexcloud.kz/tts/v3/utteranceSynthesis"
  YANDEX_TIMEOUT: "120"
  YANDEX_SSL_VERIFY: "true"
